[package]
name = "cursor-party-rewrite"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow = "1"
thiserror = "2"

time = "0.3"

bytestring = "1.4"

serde = { version = "1", features = ["derive"] }
serde_json = "1"

actix = "0.13"
actix-files = "0.6"
actix-web = "4"
actix-web-actors = "4.3"
idna_adapter = { version = "=1.0.0", optional = true } # locked to 1.0.0 to prevent pulling in a ton of unicode bullshit

futures = "0.3"
tokio = { version = "1", features = ["full"] }
